### ISSUE TITLE
Related tutorial improvements

### ISSUE THREAD

**Issue by ramonvanschaik** [jamesmcclain/onnxruntime-rocm-build#8]
Firstly, thanks for your work on this! Really got me started quickly with pytorch on my Steamdeck.

Got here via [a tutorial you wrote](https://www.element84.com/machine-learning/running-rocm-5-4-2-onnx-and-pytorch-on-a-steamdeck/). I found two issues. I was able to google my way around them, but maybe others are not.
- `sudo systemcl is-enabled docker.service` <-- t missing in `systemctl`
- When adding keys, I needed to run `sudo pacman-key --populate archlinux holo` before I could install things. Seems to be a recent change

Cheers,

**Comment by jamesmcclain** [comment]
@ramonvanschaik Many thanks for your kind words, I am glad that you enjoyed the tutorial.  That tutorial published shortly after I departed that organization, so I am not longer able to update/edit it, unfortunately.  Perhaps at some point I will publish an updated version in a different venue.

**Comment by ramonvanschaik** [comment]
Understandable! Closing...
